name: Run Web Scraper Every 2 Days

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 */2 * *'

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Download previous result data (if available)
        uses: actions/download-artifact@v4
        with:
          name: scraper-output
          path: data/
        continue-on-error: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt

      - name: Run scraper
        run: python main.py --compare-to 10_05_2025

      - name: Upload output data
        uses: actions/upload-artifact@v4
        with:
          name: scraper-output
          path: data/

